#! /usr/bin/bash

# base alias
alias \
  grep='grep --color=auto' \
  ls='ls --color=auto' \
  ll='ls -lh' \
  la='ls -lAh' \
  l='ls -lah' \
  cp='cp -iv' \
  mv='mv -iv' \
  s=neofetch \
  p="ping www.baidu.com" \
  c=clear \
  hexedit="hexedit --color" \
  fm=ranger \
  ipy=ipython \
  x="xmodmap ~/.Xmodmap && xset r rate 300 50" \
  XNORMAL="xmodmap ~/.Xmodmap_normal && xset r rate 300 50" \
  Semojis="cat ~/Nutstore\ Files/Nutstore/MARKDOWN_NOTE/.usefulfile/emoji | dmenu -i -l 20"

# git clone https://github.com/kaelzhang/shell-safe-rm.git
[ -f ~/.local/bin/shell-safe-rm/bin/rm.sh ] && alias rm="~/.local/bin/shell-safe-rm/bin/rm.sh"

# proxy alias
alias \
  SetProxy="export http_proxy=http://127.0.0.1:8118 https_proxy=http://127.0.0.1:8118" \
  UnSetProxy="unset http_proxy https_proxy"
  # wgu="sudo wg-quick up wg0" \
  # wgd="sudo wg-quick down wg0"

# video alias
alias \
  lsvideo="lspci | egrep 'VGA|3D'" \
  catvideo='glxinfo | grep "OpenGL renderer"' \
  infonvidia="nvidia-smi" \
  nvidiaup="sudo tee /proc/acpi/bbswitch <<< 'ON'" \
  nvidiadown="sudo rmmod nvidia && sudo tee /proc/acpi/bbswitch <<< OFF"

# git alias
alias \
  gcd="git clone --depth 1 " \
  gs="git status " \
  ga="git add " \
  gaa="git add -A" \
  gb="git branch " \
  gc="git commit" \
  gca="gc --amend --edit" \
  gcan="gc --amend --no-edit" \
  gd="git diff" \
  goto="git checkout" \
  gbm="git checkout master" \
  gl="git log --graph" \
  guntrack="git rm -r --cached " \
  githist="git log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short" \
  gitdump="git cat-file -p "

# tmux alias
alias \
  ntmux="tmux new -s" \
  atmux="tmux a -d -t " \
  tJ="tmux new -s jie || tmux a -d -t jie" \
  te="tmux new -s SUN || tmux a -d -t SUN"

# package-manager alias
alias \
  supiplocal="sudo pip install -i https://pypi.tuna.tsinghua.edu.cn/simple/ " \
  supipupdate="sudo pip install -i https://pypi.tuna.tsinghua.edu.cn/simple/ --upgrade " \
  piplocal="pip install --user -i https://pypi.tuna.tsinghua.edu.cn/simple/ " \
  pipupdate="pip install --user -i https://pypi.tuna.tsinghua.edu.cn/simple/ --upgrade " \
  sunpm="sudo npm --registry https://registry.npm.taobao.org install -g" \
  sunpmupdate="sudo npm --registry https://registry.npm.taobao.org update -g"

# c-index alias
alias \
  setctags="ctags -R -f .tags" \
  setcscope="cscope -Rbq"

# misc alias
alias \
  Sweather="curl wttr.in"
