#! /usr/bin/bash

# base alias
alias \
  grep='grep --color=auto' \
  egrep='egrep --color=auto' \
  fgrep='fgrep --color=auto' \
  cp='cp -iv' \
  mv='mv -iv' \
  free='free -m' \
  s=neofetch \
  S="mpv ~/Nutstore\ Files/Nutstore/others/alarm.oga" \
  p="ping -c 4 archlinux.org" \
  hexedit="hexedit --color" \
  open="xdg-open" \
  fm="~/.config/lf/lfrun" \
  lf="~/.config/lf/lfrun" \
  ipy=ipython \
  x="xmodmap ~/.Xmodmap && xset r rate 300 50" \
  XNORMAL="xmodmap ~/.Xmodmap_normal && xset r rate 300 50" \
  rm=trash \
  rml=trash-list \
  rme=trash-empty \
  du="ncdu --color dark" \
  cat="bat --number" \
  ls='exa --color=always --group-directories-first' \
  l1='exa -1 --color=always --group-directories-first' \
  ll='exa -l --color=always --group-directories-first' \
  la='exa -a --color=always --group-directories-first' \
  l='exa -la --color=always --group-directories-first' \
  lt='exa -T --color=always --group-directories-first' \
  lat='exa -aT --color=always --group-directories-first' \
  df="duf"

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
# df="df -hl"
# ls='ls --color=auto' \
# ll='ls -lh' \
# la='ls -lAh' \
# l='ls -lah' \
alias kittykeys="grep -E '^(# )?map' ~/.config/kitty/kitty.conf | sed -e 's/^# //g' -e 's/ /@/' -e 's/ /@/' -e 's/ //g' | awk -F '@' '{printf \"%-22s%-s\n\", \$2, \$3}'"
alias ydl="youtube-dl --proxy socks5://127.0.0.1:1080/ --add-metadata -i"

# git clone https://github.com/kaelzhang/shell-safe-rm.git
# [ -f ~/.local/bin/shell-safe-rm/bin/rm.sh ] && alias rm="~/.local/bin/shell-safe-rm/bin/rm.sh"

# proxy alias
alias \
  SetProxy="export http_proxy=http://127.0.0.1:8118 https_proxy=http://127.0.0.1:8118" \
  UnSetProxy="unset http_proxy https_proxy"
  # wgu="sudo wg-quick up wg0" \
  # wgd="sudo wg-quick down wg0"

# video alias
alias \
  lsvideo="lspci | egrep 'VGA|3D'" \
  catvideo='glxinfo | grep "OpenGL renderer"' \
  infonvidia="nvidia-smi" \
  nvidiaup="sudo tee /proc/acpi/bbswitch <<< 'ON'" \
  nvidiadown="sudo rmmod nvidia && sudo tee /proc/acpi/bbswitch <<< OFF"

# git alias
alias \
  gcd="git clone --depth 1 " \
  gs="git status " \
  ga="git add " \
  gaa="git add -A" \
  gb="git branch " \
  gc="git commit" \
  gca="gc --amend --edit" \
  gcan="gc --amend --no-edit" \
  gd="git diff" \
  goto="git checkout" \
  gbm="git checkout master" \
  gl="git log --graph" \
  guntrack="git rm -r --cached " \
  githist="git log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short" \
  gitdump="git cat-file -p "

# tmux alias
alias \
  ntmux="tmux new -s" \
  atmux="tmux a -d -t " \
  tJ="tmux new -s JIE || tmux a -d -t JIE" \
  ta="tmux new -s Arch || tmux a -d -t Arch"

# package-manager alias
alias \
  piplocal="pip install --user -i https://pypi.tuna.tsinghua.edu.cn/simple/ " \
  pipupdate="pip install --user -i https://pypi.tuna.tsinghua.edu.cn/simple/ --upgrade " \
  sunpm="sudo npm --registry https://registry.npm.taobao.org install -g" \
  sunpmupdate="sudo npm --registry https://registry.npm.taobao.org update -g"

# c-index alias
alias \
  setcscope="cscope -Rbq"

# misc alias
alias \
  Sweather="curl wttr.in" \
  nv="neovim" \

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# broot
alias br='broot -dhp'
alias bs='broot --sizes'

alias unlock='sudo rm /var/lib/pacman/db.lck'    # remove pacman lock
alias cleanup='sudo pacman -Rns (pacman -Qtdq)'  # remove orphaned packages
