#! /usr/bin/bash

# base alias
alias \
  grep='grep --color=auto' \
  egrep='egrep --color=auto' \
  fgrep='fgrep --color=auto' \
  cp='cp -iv' \
  mv='mv -iv' \
  free='free -m' \
  s=neofetch \
  S="mpv ~/Nutstore\ Files/Nutstore/others/alarm.oga" \
  p="ping -c 4 archlinux.org" \
  c=clear \
  hexedit="hexedit --color" \
  open="xdg-open" \
  fm=lf \
  ra=ranger \
  ipy=ipython \
  x="xmodmap ~/.Xmodmap && xset r rate 300 50" \
  XNORMAL="xmodmap ~/.Xmodmap_normal && xset r rate 300 50" \
  Semojis="cat ~/Nutstore\ Files/Nutstore/MARKDOWN_NOTE/.usefulfile/emoji | dmenu -i -l 20" \
  rm=trash \
  rml=trash-list \
  rme=trash-empty \
  du="ncdu --color dark" \
  cat="bat --number" \
  sc=sc-im \
  ls='exa --color=always --group-directories-first' \
  l1='exa -1 --color=always --group-directories-first' \
  ll='exa -l --color=always --group-directories-first' \
  la='exa -a --color=always --group-directories-first' \
  l='exa -la --color=always --group-directories-first' \
  lt='exa -T --color=always --group-directories-first' \
  lat='exa -aT --color=always --group-directories-first' \
  df="duf"

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
# df="df -hl"
# ls='ls --color=auto' \
# ll='ls -lh' \
# la='ls -lAh' \
# l='ls -lah' \
alias kittykeys="grep -E '^(# )?map' .config/kitty/kitty.conf | sed -e 's/^# //g' -e 's/ /@/' -e 's/ /@/' -e 's/ //g' | awk -F '@' '{printf \"%-22s%-s\n\", \$2, \$3}'"

# git clone https://github.com/kaelzhang/shell-safe-rm.git
[ -f ~/.local/bin/shell-safe-rm/bin/rm.sh ] && alias rm="~/.local/bin/shell-safe-rm/bin/rm.sh"

# proxy alias
alias \
  SetProxy="export http_proxy=http://127.0.0.1:8118 https_proxy=http://127.0.0.1:8118" \
  UnSetProxy="unset http_proxy https_proxy"
  # wgu="sudo wg-quick up wg0" \
  # wgd="sudo wg-quick down wg0"

# video alias
alias \
  lsvideo="lspci | egrep 'VGA|3D'" \
  catvideo='glxinfo | grep "OpenGL renderer"' \
  infonvidia="nvidia-smi" \
  nvidiaup="sudo tee /proc/acpi/bbswitch <<< 'ON'" \
  nvidiadown="sudo rmmod nvidia && sudo tee /proc/acpi/bbswitch <<< OFF"

# git alias
alias \
  gcd="git clone --depth 1 " \
  gs="git status " \
  ga="git add " \
  gaa="git add -A" \
  gb="git branch " \
  gc="git commit" \
  gca="gc --amend --edit" \
  gcan="gc --amend --no-edit" \
  gd="git diff" \
  goto="git checkout" \
  gbm="git checkout master" \
  gl="git log --graph" \
  guntrack="git rm -r --cached " \
  githist="git log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short" \
  gitdump="git cat-file -p "

# tmux alias
alias \
  ntmux="tmux new -s" \
  atmux="tmux a -d -t " \
  tJ="tmux new -s jie || tmux a -d -t jie" \
  te="tmux new -s SUN || tmux a -d -t SUN"

# package-manager alias
alias \
  supiplocal="sudo pip install -i https://pypi.tuna.tsinghua.edu.cn/simple/ " \
  supipupdate="sudo pip install -i https://pypi.tuna.tsinghua.edu.cn/simple/ --upgrade " \
  piplocal="pip install --user -i https://pypi.tuna.tsinghua.edu.cn/simple/ " \
  pipupdate="pip install --user -i https://pypi.tuna.tsinghua.edu.cn/simple/ --upgrade " \
  sunpm="sudo npm --registry https://registry.npm.taobao.org install -g" \
  sunpmupdate="sudo npm --registry https://registry.npm.taobao.org update -g"

# c-index alias
alias \
  setctags="ctags -R -f .tags" \
  setcscope="cscope -Rbq"

# misc alias
alias \
  Sweather="curl wttr.in" \
  nv="neovim" \
  vi="vim" \
  em="emacs -nw" \
  Emacs="emacsclient -n " \
  doomsync="~/.emacs.d/bin/doom sync" \
  doomdoctor="~/.emacs.d/bin/doom doctor" \
  doomupgrade="~/.emacs.d/bin/doom upgrade" \
  doompurge="~/.emacs.d/bin/doom purge" \
  doomclean="~/.emacs.d/bin/doom clean"

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# broot
alias br='broot -dhp'
alias bs='broot --sizes'

# pacman and yay
alias pacsyu='sudo pacman -Syyu'                 # update only standard pkgs
alias yaysua='yay -Sua --noconfirm'              # update only AUR pkgs (yay)
alias yaysyu='yay -Syu --noconfirm'              # update standard pkgs and AUR pkgs (yay)
alias parsua='paru -Sua --noconfirm'             # update only AUR pkgs (paru)
alias parsyu='paru -Syu --noconfirm'             # update standard pkgs and AUR pkgs (paru)
alias unlock='sudo rm /var/lib/pacman/db.lck'    # remove pacman lock
alias cleanup='sudo pacman -Rns (pacman -Qtdq)'  # remove orphaned packages

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
