#!/bin/sh

# Prints the current volume or 🔇 if muted.

[ $(pamixer --get-mute) = true ] && echo 🔇 && exit

vol="$(pamixer --get-volume)"

while [ "$?" -ne "0" ]; do
  vol="$(pamixer --get-volume)"
done

if [ "$vol" -gt "70" ]; then
  icon="🔊"
elif [ "$vol" -lt "30" ]; then
  icon="🔈"
else
  icon="🔉"
fi

echo "$icon$vol%"
