#!/usr/bin/env bash

set -xe

path=$(cd $(dirname "$0") && pwd)

mkdir -p "$HOME/.vim"

ln -sf "$path/statusline.vim" "$HOME/.vim/statusline.vim"
ln -sf "$path/colors/" "$HOME/.vim/colors"
cp -f "$path/vimrc" "$HOME/.vimrc"
chmod 400 "$HOME/.vimrc"
