#!/usr/bin/env python3

import argparse
import vmess
import clash
import vless
import os

def main():
    parser = argparse.ArgumentParser(
            prog="conv",
            description="Convert config file to clash config file"
            )
    parser.add_argument("-l", "--link", action='store')
    parser.add_argument("-f", "--file", action='store')
    parser.add_argument("-o", "--output", action='store')
    args = parser.parse_args()
    if args.file != None:
        print("TODO: extract file has not been implented yet!!!")
        return
    else:
        if args.link == None:
            print("./conv -l link://...")
            return
        if args.link[:8] == "vmess://":
            name, node = vmess.vmess2clash(args.link)
        elif args.link[:8] == "vless://":
            name, node = vless.vless2clash(args.link)

        if name != None and node != None:
            clash.append_node(name, node)

    opath = os.path.expanduser("~/config.yaml" if args.output == None else args.output)

    clash.gen_clash_conf(opath)


if __name__ == "__main__":
    main()
