#! /usr/bin/bash

# base alias
alias \
  grep='grep --color=auto' \
  egrep='egrep --color=auto' \
  fgrep='fgrep --color=auto' \
  cp='cp -iv' \
  mv='mv -iv' \
  free='free -m' \
  s=neofetch \
  S="mpv ~/Nutstore\ Files/Nutstore/others/alarm.oga" \
  p="ping -c 4 archlinux.org" \
  hexedit="hexedit --color" \
  open="xdg-open" \
  fm="~/.config/lf/lfrun" \
  lf="~/.config/lf/lfrun" \
  ipy=ipython \
  rm=trash \
  rml=trash-list \
  rme=trash-empty \
  rmr=trash-restore \
  du="ncdu --color dark" \
  cat="bat --number" \
  ls='exa --color=always --group-directories-first' \
  l1='exa -1 --color=always --group-directories-first' \
  ll='exa -l --color=always --group-directories-first' \
  la='exa -a --color=always --group-directories-first' \
  l='exa -la --color=always --group-directories-first' \
  lt='exa -T --color=always --group-directories-first' \
  lat='exa -aT --color=always --group-directories-first' \
  ldf="duf --only local" \
  df="duf"
  # x="xmodmap ~/.Xmodmap && xset r rate 300 50" \
  # XNORMAL="xmodmap ~/.Xmodmap_normal && xset r rate 300 50" \

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
# alias df="df -hl"
# alias ls='ls --color=auto'
# alias ll='ls -lh'
# alias la='ls -lAh'
# alias l='ls -lah'
alias kittykeys="grep -E '^(# )?map' ~/.config/kitty/kitty.conf | sed -e 's/^# //g' -e 's/ /@/' -e 's/ /@/' -e 's/ //g' | awk -F '@' '{printf \"%-22s%-s\n\", \$2, \$3}'"
alias ydlproxy="youtube-dl --proxy socks5://127.0.0.1:1080/ --add-metadata -i"
alias ydl="youtube-dl --add-metadata -i"

# proxy alias
alias \
  SetProxy="export http_proxy=http://127.0.0.1:8118 https_proxy=http://127.0.0.1:8118" \
  UnSetProxy="unset http_proxy https_proxy"
  # wgu="sudo wg-quick up wg0" \
  # wgd="sudo wg-quick down wg0"

# video alias
alias \
  lsvideo="lspci | egrep 'VGA|3D'" \
  catvideo='glxinfo | grep "OpenGL renderer"' \
  infonvidia="nvidia-smi" \
  nvidiaup="sudo tee /proc/acpi/bbswitch <<< 'ON'" \
  nvidiadown="sudo rmmod nvidia && sudo tee /proc/acpi/bbswitch <<< OFF"

# git alias
alias \
  gcd="git clone --depth 1 " \
  gs="git status " \
  ga="git add " \
  gaa="git add -A" \
  gb="git branch " \
  gc="git commit" \
  gca="gc --amend --edit" \
  gcan="gc --amend --no-edit" \
  gd="git diff" \
  goto="git checkout" \
  gbm="git checkout master" \
  gl="git log --graph --all" \
  guntrack="git rm -r --cached " \
  githist="git log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short" \
  gitdump="git cat-file -p "

# tmux alias
alias \
  tJ="tmux new -s Jie || tmux a -d -t Jie" \
  tA="tmux new -s Arch || tmux a -d -t Arch"

# package-manager alias
# https://www.activestate.com/resources/quick-reads/how-to-update-all-python-packages/
alias \
  lpip="pip3 install --user -i https://pypi.tuna.tsinghua.edu.cn/simple/" \
  lpiplist="pip3 list --user" \
  lpipupdate="pip3 install --user -i https://pypi.tuna.tsinghua.edu.cn/simple/ --upgrade" \
  lpipautoupdate="pip3 list --outdated --format=freeze --user -i https://pypi.tuna.tsinghua.edu.cn/simple/ | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U -i https://pypi.tuna.tsinghua.edu.cn/simple/ --user" \
  lpipoutofdate="pip3 list --user -i https://pypi.tuna.tsinghua.edu.cn/simple/ --outdated"
alias \
  gnpm="sudo npm --registry https://registry.npm.taobao.org install -g" \
  gnpmlist="npm list -g" \
  gnpmupdate="sudo npm --registry https://registry.npm.taobao.org update -g" \
  gnpmoutofdate="npm --registry https://registry.npm.taobao.org outdated -g"

# c-index alias
alias \
  setcscope="cscope -Rbq"

# misc alias
alias \
  Sweather="curl wttr.in" \
  nv="neovim" \

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# broot
alias br='broot -dhp'
alias bs='broot --sizes'

alias unlock='sudo rm /var/lib/pacman/db.lck'    # remove pacman lock
alias cleanup='sudo pacman -Rns $(pacman -Qtdq) 2> /dev/null'  # remove orphaned packages

# network-wifi
alias \
  nshow="nmcli device show | grep CONNECTION | grep -v '\-\-' | awk -F ' ' '{print \$NF}'" \
  nlist="nmcli device wifi list" \
  nconn="nmcli device wifi connect" \
  publicip="curl https://ipinfo.io/ip; echo"

alias alacritty0="sed -i -e 's/\(^background_opacity:\) 1.0/\1 0.7/' ~/.config/alacritty/alacritty.yml"
alias alacritty1="sed -i -e 's/\(^background_opacity:\) 0.7/\1 1.0/' ~/.config/alacritty/alacritty.yml"

alias luamake=/home/red/.cache/nvim/lua-language-server/3rd/luamake/luamake
