#!/bin/sh

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

batorcat() {
  file="$1"
  shift
  if command -v bat > /dev/null 2>&1
  then
    bat --color=always --style=plain --pager=never "$file" "$@"
  else
    cat "$file"
  fi
}

case "$(file --dereference --brief --mime-type -- "$1")" in
  text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1" ;;
  text/troff) man ./ "$1" | col -b ;;
  text/* | */xml | application/json) batorcat "$1" --terminal-width "$(($4-2))" ;;
  application/zip) atool --list -- "$1" ;;
  image/*) chafa "$1" -s "$2"x"$3" ;;
  audio/* | video/*) mediainfo "$1" ;;
  application/pgp-encrypted) gpg -d -- "$1" ;;
esac
