#!/usr/bin/env bash

set -e

RESET="\e[0m"
RED="\e[1;31m"
GREEN="\e[1;32m"
YELLOW="\e[1;33m"
CYAN="\e[36m"

GR_URL="https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/"

TARGET_DIR="$HOME/.config/mihomo/"

main() {
  if [[ -z "$1" ]]; then
    echo "Usage:"
    echo -e "\t$0 \e[36mgeoip_metadb\e[0m"
    echo -e "\t$0 \e[36mgeoip_dat\e[0m"
    echo -e "\t$0 \e[36mgeosite_dat\e[0m"
    echo -e "\t$0 \e[36mall\e[0m"
    echo -e "\t$0 \e[36mclear_all\e[0m"
  else
    eval "$1"
  fi
}

all() {
  geoip_metadb
  geoip_dat
  geosite_dat
}

dd() {
  TARGET_NAME=$1
  SRC_NAME=$2
  FILE_P="$TARGET_DIR""$TARGET_NAME"
  rm -rf "$FILE_P"
  F_URL="$GR_URL""$SRC_NAME"
  SHA_URL="$GR_URL""$SRC_NAME"".sha256sum"
  TEMP_SHA_FILE=$(mktemp /tmp/clash_meta_metafile_"$SRC_NAME".XXXXXXXXXX)
  wget --quiet --show-progress --continue "$F_URL" -O "$FILE_P"
  wget --quiet --show-progress --continue "$SHA_URL" -O "$TEMP_SHA_FILE"
  if echo "$(cat $TEMP_SHA_FILE | cut -d' ' -f1) $FILE_P" | sha256sum --check --status; then
    rm -rf $TEMP_SHA_FILE
    echo -e "${GREEN}INFO${RESET}: ${YELLOW}${FILE_P}${RESET} downloading finished!!!"
  else
    echo -e "${RED}ERROR${RESET}: ${CYAN}${FILE_P}${RESET} sha256sum check failed, the sha256sum file is located at ${CYAN}${TEMP_SHA_FILE}${RESET}"
  fi
}

geoip_metadb() {
  TARGET_NAME="GeoIP.metadb"
  SRC_NAME="geoip.metadb"
  dd "$TARGET_NAME" "$SRC_NAME"
}

geoip_dat() {
  TARGET_NAME="GeoIP.dat"
  SRC_NAME="geoip.dat"
  dd "$TARGET_NAME" "$SRC_NAME"
}

geosite_dat() {
  TARGET_NAME="GeoSite.dat"
  SRC_NAME="geosite.dat"
  dd "$TARGET_NAME" "$SRC_NAME"
}

clear_all() {
  FILE_P1="$TARGET_DIR""GeoIP.metadb"
  FILE_P2="$TARGET_DIR""GeoIP.dat"
  FILE_P3="$TARGET_DIR""GeoSite.dat"
  rm -rf "$FILE_P1" "$FILE_P2" "$FILE_P3"
}

main "$@"
