#! /usr/bin/bash

# base alias
alias \
  grep='grep --color=auto' \
  cp='cp -iv' \
  mv='mv -iv' \
  diff='diff --color -u' \
  s="neofetch" \
  d="date" \
  S="mpv ~/Downloads/GDrive/others/alarm.oga" \
  cg="curl -v google.com" \
  hexedit="hexedit --color" \
  open="xdg-open" \
  sudo="sudo -E" \
  fm="~/.config/lf/lfrun" \
  lf="~/.config/lf/lfrun" \
  rm="gio trash" \
  rml="gio trash --list" \
  rme="gio trash --empty"\
  rmr="gio trash --restore" \
  du="ncdu --color dark" \
  cat="bat --style=plain" \
  ls='exa --color=always --group-directories-first' \
  ll='exa -lhg --color=always --group-directories-first' \
  l='exa -lhga --color=always --group-directories-first' \
  tree='exa --color=always --tree' \
  ldf="duf --only local" \
  gpc="gpaste-client" \
  gdrive="rclone sync ~/Downloads/GDrive GDrive:GDrive" \
  a8="aria2c -x 8" \
  pc="env | grep --color=never proxy"

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'

# alias s1="sxiv -b -N 'DingImage' $(ls -1 --color=never ~/Screenshot/pic-DingImage-* | tail -n 1)"

alias \
  ydl="youtube-dl --add-metadata -i -f bestvideo+bestaudio" \
  ydla8="youtube-dl --add-metadata -i -f bestvideo+bestaudio --external-downloader aria2c --external-downloader-args '-x 8'" \

# proxy alias
alias \
  SetProxy="source ~/dotfiles/my_script/setTermProxy" \
  # wgu="sudo wg-quick up wg0" \
  # wgd="sudo wg-quick down wg0"

# video alias
alias \
  lsvideo="lspci | egrep 'VGA|3D'" \
  catvideo='glxinfo | grep "OpenGL renderer"' \
  infonvidia="nvidia-smi" \
  nvidiaup="sudo tee /proc/acpi/bbswitch <<< 'ON'" \
  nvidiadown="sudo tee /proc/acpi/bbswitch <<< OFF"

# git alias
alias \
  gs="git status" \
  gd="git diff" \
  goto="git switch" \
  gca="git commit --amend --edit" \
  gcan="git commit --amend --no-edit" \
  gcount="git rev-list --count"

# tmux alias
alias \
  tJ="tmux new -s Jie || tmux a -d -t Jie" \
  tA="tmux new -s Arch || tmux a -d -t Arch" \
  tj="tmux new -s jsj || tmux a -d -t jsj"

alias \
  stodo="glow ~/Downloads/GDrive/todo.md" \
  etodo="$EDITOR ~/Downloads/GDrive/todo.md" \

# misc alias
alias \
  Sweather="curl wttr.in" \
  cht="curl cht.sh" \
  vi="vim" \
  nv="nvim"

alias unlock='sudo rm /var/lib/pacman/db.lck'    # remove pacman lock
alias cleanup='sudo pacman -Rns $(pacman -Qtdq) 2> /dev/null'  # remove orphaned packages

# network-wifi
alias \
  nshow="nmcli device show" \
  nlist="nmcli device wifi list" \
  nconn="nmcli device wifi connect" \
  publicip="curl https://ipinfo.io/ip; echo"

# bluetooth
alias \
  btl=bluetoothctl \
  btlpn="bluetoothctl power on" \
  btlpf="bluetoothctl power off" \
  btlsn="bluetoothctl scan on" \
  btlc="bluetoothctl connect" \
  btldc="bluetoothctl disconnect"

alias alacritty0="sed -i -e 's/\(^\W*opacity:\) 1.0/\1 0.95/' ~/.config/alacritty/alacritty.yml"
alias alacritty1="sed -i -e 's/\(^\W*opacity:\) 0.95/\1 1.0/' ~/.config/alacritty/alacritty.yml"

alias sw="devour"

alias gbclear='xsel -cb; gpc delete $(gpc | head -n 1 | cut -d ":" -f1)'


# docker run
[ -f $HOME/Downloads/docker_use/dockerrun ] && source $HOME/Downloads/docker_use/dockerrun
