#! /usr/bin/bash

# base alias
alias \
  grep='grep --color=auto' \
  egrep='egrep --color=auto' \
  fgrep='fgrep --color=auto' \
  cp='cp -iv' \
  mv='mv -iv' \
  free='free -m' \
  s="neofetch | lolcat -t" \
  S="mpv ~/Nutstore\ Files/Nutstore/others/alarm.oga" \
  p="ping -c 4 archlinux.org" \
  cg="curl -v google.com" \
  hexedit="hexedit --color" \
  open="xdg-open" \
  sudo="sudo -E" \
  fm="~/.config/lf/lfrun" \
  lf="~/.config/lf/lfrun" \
  rm=trash \
  rml=trash-list \
  rme='trash-empty -f'\
  rmr=trash-restore \
  du="ncdu --color dark" \
  cat="bat --style=plain" \
  ls='exa --color=always --group-directories-first' \
  l1='exa -1 --color=always --group-directories-first' \
  ll='exa -lhg --color=always --group-directories-first' \
  la='exa -a --color=always --group-directories-first' \
  l='exa -lhga --color=always --group-directories-first' \
  lt='exa -T --color=always --group-directories-first' \
  tree='exa --color=always --tree' \
  lat='exa -aT --color=always --group-directories-first' \
  ldf="duf --only local" \
  df="duf"
  # x="xmodmap ~/.Xmodmap && xset r rate 300 50" \
  # XNORMAL="xmodmap ~/.Xmodmap_normal && xset r rate 300 50" \

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias sm="smem --pie name -c pss"
# alias df="df -hl"
# alias ls='ls --color=auto'
# alias ll='ls -lh'
# alias la='ls -lAh'
# alias l='ls -lah'
# alias s1="sxiv -b -N 'DingImage' $(ls -1 --color=never ~/Screenshot/pic-DingImage-* | tail -n 1)"

alias \
  ydlproxy="youtube-dl --proxy socks5://127.0.0.1:1080/ --add-metadata -i -f bestvideo+bestaudio" \
  ydl="youtube-dl --add-metadata -i -f bestvideo+bestaudio" \
  ydla8="youtube-dl --add-metadata -i -f bestvideo+bestaudio --external-downloader aria2c --external-downloader-args '-x 8'" \
  ydlist="youtube-dl --add-metadata -i -F"

# proxy alias
alias \
  SetProxy="source ~/dotfiles/my_script/setTermProxy" \
  # wgu="sudo wg-quick up wg0" \
  # wgd="sudo wg-quick down wg0"

# video alias
alias \
  lsvideo="lspci | egrep 'VGA|3D'" \
  catvideo='glxinfo | grep "OpenGL renderer"' \
  infonvidia="nvidia-smi" \
  nvidiaup="sudo tee /proc/acpi/bbswitch <<< 'ON'" \
  nvidiadown="sudo tee /proc/acpi/bbswitch <<< OFF"

# git alias
alias \
  gcd="git clone --depth 1 " \
  gs="git status " \
  ga="git add " \
  gaa="git add -A" \
  gb="git branch " \
  gbl="git branch -l" \
  gc="git commit" \
  gca="gc --amend --edit" \
  gcan="gc --amend --no-edit" \
  gd="git diff" \
  goto="git checkout" \
  gbm="git checkout master" \
  guntrack="git rm -r --cached " \
  githist="git log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short" \
  gitdump="git cat-file -p " \
  gl=tig
  # gl="git log --graph --all" \

# tmux alias
alias \
  tJ="tmux new -s Jie || tmux a -d -t Jie" \
  tA="tmux new -s Arch || tmux a -d -t Arch" \
  tj="tmux new -s jsj || tmux a -d -t jsj"

# package-manager alias
# https://www.activestate.com/resources/quick-reads/how-to-update-all-python-packages/
alias \
  py=python \
  gpip="pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple/" \
  gpipupdate="pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple/ --upgrade" \
  gpipoutofdate="pip3 list -i https://pypi.tuna.tsinghua.edu.cn/simple/ --outdated" \
  pyctags="ctags -R --fields=+l --languages=python --python-kinds=-iv -f ./tags ./" \
alias \
  gnpm="sudo npm --registry https://registry.npm.taobao.org install -g" \
  gnpmlist="npm list -g" \
  gnpmupdate="sudo npm --registry https://registry.npm.taobao.org update -g" \
  gnpmoutofdate="npm --registry https://registry.npm.taobao.org outdated -g"

alias \
  stodo="glow ~/Nutstore\ Files/Nutstore/todo.md" \
  etodo="$EDITOR ~/Nutstore\ Files/Nutstore/todo.md" \

# c-index alias
alias \
  setcscope="cscope -Rbq"

# misc alias
alias \
  Sweather="curl wttr.in" \
  nv="nvim" \

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# broot
# alias br='broot -dhp'
# alias bs='broot --sizes'

alias unlock='sudo rm /var/lib/pacman/db.lck'    # remove pacman lock
alias cleanup='sudo pacman -Rns $(pacman -Qtdq) 2> /dev/null'  # remove orphaned packages

# network-wifi
alias \
  nshow="nmcli device show" \
  nlist="nmcli device wifi list" \
  nconn="nmcli device wifi connect" \
  publicip="curl https://ipinfo.io/ip; echo"

# bluetooth
alias \
  btl=bluetoothctl \
  btlpn="bluetoothctl power on" \
  btlpf="bluetoothctl power off" \
  btlsn="bluetoothctl scan on" \
  btlc="bluetoothctl connect" \
  btldc="bluetoothctl disconnect"

alias alacritty0="sed -i -e 's/\(^\W*opacity:\) 1.0/\1 0.7/' ~/.config/alacritty/alacritty.yml"
alias alacritty1="sed -i -e 's/\(^\W*opacity:\) 0.7/\1 1.0/' ~/.config/alacritty/alacritty.yml"

alias sw="devour"

alias gbtoken="head ~/Nutstore\ Files/Nutstore/github/token -n 1 | awk -F '\n' '{printf \$1}' | xsel -ib"
alias gbclear="xsel -cb; copyq remove ROWS=1"
