all:
	@echo "使用--always-make强制make执行"
	@echo "将一些脚本链接到~/.local/bin/"

install:
	@ln -s ~/.usefulscript/dwm-status.sh ~/.local/bin/dwm-status.sh
	@ln -s ~/.usefulscript/maimpick ~/.local/bin/maimpick
	@ln -s ~/.usefulscript/ext ~/.local/bin/ext
	@ln -s ~/.usefulscript/linkhandler ~/.local/bin/linkhandler
	@ln -s ~/.usefulscript/texclear ~/.local/bin/texclear
	@ln -s ~/.usefulscript/ifinstalled ~/.local/bin/ifinstalled
