#! /usr/bin/env sh

ClashConf=$HOME/.config/clash/

# url="https://raw.fastgit.org/yu-steven/openit/main/Clash.yaml"
url="https://raw.githubusercontent.com/yu-steven/openit/main/Clash.yaml"
# url="https://raw.githubusercontent.com/learnhard-cn/free_proxy_ss/main/config.yaml"

if [ ! -d "${ClashConf}/clash-dashboard" ]; then
  echo run $'\e[36m'git clone -b gh-pages https://github.com/Dreamacro/clash-dashboard.git ~/.config/clash/clash-dashboard$'\e[0m' to install the clash web ui
else
  wget -q $url -O ${ClashConf}/config.yaml
  sed -i -e "s@\(^external-controller:.*\)@\1\nexternal-ui: $HOME/.config/clash/clash-dashboard@g" ${ClashConf}/config.yaml
  sudo systemctl restart clash.service
  sudo systemctl status clash.service
fi
