#! /usr/bin/env sh

ClashConf=$HOME/.config/clash/

if [ ! -d "${ClashConf}/clash-dashboard" ]; then
  echo run $'\e[36m'git clone -b gh-pages https://github.com/Dreamacro/clash-dashboard.git ~/.config/clash/clash-dashboard$'\e[0m' to install the clash web ui
else
  wget -q https://openit.ml/Clash.yaml -O ${ClashConf}/config.yaml
  sed -i -e "s@\(^external-controller:.*\)@\1\nexternal-ui: $HOME/.config/clash/clash-dashboard@g" ${ClashConf}/config.yaml
  sudo systemctl restart clash.service
  sudo systemctl status clash.service
fi
