#!/bin/sh

# The famous "get a menu of emojis to copy" script.

VER='13.1'
URL="https://www.unicode.org/Public/emoji/${VER}/emoji-test.txt"
DIR="$HOME/.cache"
FILE="$DIR/emojis.txt"

if [ ! -r $FILE ]
then
  if [ ! -d $DIR ]; then mkdir $DIR; fi
  curl --compressed "$URL" | sed -nE 's/^.+fully-qualified\s+#\s(\S+) E[0-9.]+ / \1 /p' > "$FILE"
fi


# Get user selection via dmenu from emoji file.
# chosen=$(cut -d ';' -f1 $FILE | dmenu -i -l 20 | sed "s/ .*//")
chosen=$(cut -f1 $FILE | dmenu -i -l 20 | cut -d ' ' -f2)

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
  xdotool type "$chosen"
else
  echo "$chosen" | tr -d '\n' | xclip -selection clipboard
  notify-send "'$chosen' copied to clipboard." &
fi
