#!/usr/bin/env sh

ifinstalled "fortune" || exit
ifinstalled "cowsay" || exit
ifinstalled "lolcat" || exit

PREFIX="fortune | cowsay -f "
SUFFIX=" | lolcat"
STYLE=("beavis.zen" "blowfish" "bong" "bud-frogs" "bunny" "cheese" "cower" "daemon" "default" "dragon" "dragon-and-cow" "elephant" "elephant-in-snake" "eyes" "flaming-sheep" "ghostbusters" "head-in" "hellokitty" "kiss" "kitty" "koala" "kosh" "luke-koala" "meow" "milk" "moofasa" "moose" "mutilated" "ren" "satanic" "sheep" "skeleton" "small" "sodomized" "stegosaurus" "stimpy" "supermilker" "surgery" "telebears" "three-eyes" "turkey" "turtle" "tux" "udder" "vader" "vader-koala" "www")

eval $PREFIX${STYLE[$RANDOM%${#STYLE[@]}]}$SUFFIX
