#!/usr/bin/sh

if [ "$#" == 0 ]; then
  echo "Here is nothing to do. Must input a process name."
  exit
fi

smem -c pss -P "$1" -k -t | tail -n 1

# `-c` 指定要显示的列, `pas` 显示进程分配的内存
# `-P` 指定进程
# `-k` human-readable
# `-t` 开关显示总数
