#!/usr/bin/env bash

shopt -s nullglob globstar

dmenu=dmenu

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")

[[ -n $password ]] || exit

pass show "$password" | head -n 2 | tail -n 1 | sed -z 's/user: \(.*\)\n/\1/' | xsel -ib 2> /dev/null
