#!/usr/bin/env bash

shopt -s nullglob globstar

if [[ -n $WAYLAND_DISPLAY ]]; then
  dmenu=dmenu-wl
  xdotool="ydotool type --file -"
elif [[ -n $DISPLAY ]]; then
  dmenu=dmenu
  xdotool="xdotool type --clearmodifiers --file -"
else
  echo "Error: No Wayland or X11 display detected" >&2
  exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")

[[ -n $password ]] || exit

pass show $password | head -n 2 | tail -n 1 | sed -z 's/user: \(.*\)\n/\1/' | xsel -ib 2> /dev/null
