#!/usr/bin/env bash

# install `glib2` `gvfs`
ifinstalled "gio" | exit

chosen=$(gio trash --list | cut -f2 | nl -s ' > ' | dmenu -i -l 30 | cut -d '>' -f1)

if [[ -n "$chosen" ]]; then
  recover=$(gio trash --list | sed -n "${chosen}p" | cut -f1)
  gio trash --restore $recover
  echo recover file $'\e[36m'$recover$'\e[0m'
fi
