#!/usr/bin/bash

ifinstalled "xwallpaper" || exit

# function
function change_background() {
  [ "$(basename $1)" == "red_wallpaper" ] || ln -sf $1 $HOME/.config/red_wallpaper
  xwallpaper --zoom $HOME/.config/red_wallpaper > /dev/null 2>&1
}

function regularly_change_background() {
  Index=(1 1 1 1 1 1 2 2 3 4 5 6 7 8 9 10 11 12 13 14 15 15 16 16)
  change_background $HOME/Downloads/wallpaper/03_Mojave/mojave_dynamic_${Index[$(date '+%_H')]}.jpeg
}

# running
if [ "$#" -gt 0 ]; then
  if [ -e $1 ] && [ -f $1 ]; then
    change_background $1 || echo "文件必需是图片"
  else
    echo "文件不存在"
  fi
else
  while true; do
    regularly_change_background
    let wa=60-"$(date '+%_M')"
    sleep $wa"m"
  done
fi
