#!/usr/bin/env bash

if [ $# -le 0 ]; then
  echo "必需传入源文件"
  exit
fi

ifinstalled "ctags" || exit

gcc -M "$@" | sed -e 's/[\\ ]/\n/g' | \
  sed -e '/^$/d' -e '/\.o:[ \t]*$/d' | \
  ctags -R -L - --c-kinds=+p --fields=+S --extras=+q
