#!/usr/bin/env bash

prefix=http://127.0.0.1
default_port=20171
default_proxy=${prefix}:${default_port}

if [ $# -eq 0 ]; then
  if env | grep -q ^http_proxy=
  then
    unset http_proxy https_proxy all_proxy
    echo "unset 'http_proxy', 'https_proxy' and 'all_proxy'"
  else
    export http_proxy=${default_proxy} https_proxy=${default_proxy} all_proxy=${default_proxy}
    echo 'http_proxy='$http_proxy
    echo 'https_proxy='$https_proxy
    echo 'all_proxy='$all_proxy
  fi
else
  if [[ $1 =~ ^[0-9]+$ ]]; then
    if [[ $1 -gt 0 && $1 -lt 65535 ]]; then
      export http_proxy=${prefix}:$1 https_proxy=${prefix}:$1 all_proxy=${prefix}:$1
      echo 'http_proxy='"$http_proxy"
      echo 'https_proxy='"$https_proxy"
      echo 'all_proxy='"$all_proxy"
    else
      echo "The input number must greater then 0 and less then 65535"
    fi
  else
    echo "The input must be number!!!"
  fi
fi
