#! /usr/bin/env sh

ClashConf=$HOME/.config/clash/

url="https://raw.fastgit.org/yu-steven/openit/main/Clash.yaml"

# url="https://raw.githubusercontent.com/yu-steven/openit/main/Clash.yaml"
# url="https://raw.githubusercontent.com/learnhard-cn/free_proxy_ss/main/clash/config.yaml"

if [ ! -d "${ClashConf}/clash-dashboard" ]; then
  echo run $'\e[36m'git clone -b gh-pages https://github.com/Dreamacro/clash-dashboard.git ~/.config/clash/clash-dashboard$'\e[0m' to install the clash web ui
else
  wget -q $url -O ${ClashConf}/config_new.yaml
  sed -i -e "s@\(^external-controller:.*\)@\1\nexternal-ui: $HOME/.config/clash/clash-dashboard@g" ${ClashConf}/config_new.yaml
  clash -t -f ${ClashConf}/config_new.yaml > /dev/null 2>&1
  if [ $? -ne 0 ]; then
    rm ${ClashConf}/config_new.yaml
    echo "The new config file has an error, then do nothing."
    exit
  fi
  mv -f ${ClashConf}/config_new.yaml ${ClashConf}/config.yaml
  systemctl --user restart clash.service
  systemctl --user status clash.service
fi
