all:
	@echo "使用--always-make强制make执行"
	@echo "install: 将当前目录下的脚本链接到~/.local/bin/"

install:
	@ln -sf $(HOME)/.config/my_script/maimpick ~/.local/bin/maimpick
	@ln -sf $(HOME)/.config/my_script/ext ~/.local/bin/ext
	@ln -sf $(HOME)/.config/my_script/linkhandler ~/.local/bin/linkhandler
	@ln -sf $(HOME)/.config/my_script/texclear ~/.local/bin/texclear
	@ln -sf $(HOME)/.config/my_script/ifinstalled ~/.local/bin/ifinstalled
	@ln -sf $(HOME)/.config/my_script/lmc ~/.local/bin/lmc
	@ln -sf $(HOME)/.config/my_script/dmenuunicode ~/.local/bin/dmenuunicode
	@ln -sf $(HOME)/.config/my_script/Screenkey ~/.local/bin/Screenkey
	@ln -sf $(HOME)/.config/my_script/lf-select ~/.local/bin/lf-select
	@ln -sf $(HOME)/.config/my_script/rotdir ~/.local/bin/rotdir
	@ln -sf $(HOME)/.config/my_script/setrtags ~/.local/bin/setrtags
	@ln -sf $(HOME)/.config/my_script/set-bg ~/.local/bin/set-bg
	@echo "执行成功"
