#!/usr/bin/bash

# Fix Gnome Apps Slow Start due to failing services
# Add this when you include "flatpak" in your system
# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
# xset r rate 300 50 &  # Speed xrate up

# xautolock -time 30 -locker slock &

xcompmgr &
# LANG=zh_CN.UTF-8 activate-linux &

# set-bg "$HOME/.config/red_wallpaper" &
set-bg &

sxhkd &
dunst &
unclutter &
cbatticon &  # battery
gpaste-client start &
fcitx5 &
# blueman-applet &  # for bluetooth

# remaps &

dwmblocks &
