#!/usr/bin/bash

# https://mywiki.wooledge.org/DotFiles

# fcitx5
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus
export INPUT_METHOD=fcitx

export QT_QPA_PLATFORMTHEME=qt5ct  # qt theme
export TERMINAL=st
export BROWSER=${BROWSER:-firefox}
export SUDO_ASKPASS="$HOME/dots/scripts/rofi_askpass"

pipewire &

# Fix Gnome Apps Slow Start due to failing services
# Add this when you include "flatpak" in your system
# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
# xset r rate 300 50 &  # Speed xrate up

# xautolock -time 30 -locker slock &

xcompmgr &

set-bg "$HOME/.config/red_wallpaper" &
# set-bg &

sxhkd &
dunst &
unclutter &
cbatticon &  # battery
clipmenud &
fcitx5 &

blueman-applet &  # for bluetooth package is `blueman`

remaps &

dwmblocks &
