#!/usr/bin/env bash

# https://github.com/MetaCubeX/mihomo/releases
# https://phoenixnap.com/kb/git-list-tags

set -e

RESET="\e[0m"
RED="\e[1;31m"
GREEN="\e[1;32m"
YELLOW="\e[1;33m"
CYAN="\e[36m"

TARGET_DIR=~/.local/bin
TARGET_PATH=$TARGET_DIR/clash-meta.gz
TEMP_PATH=/tmp/jsj_download_clash-meta_tempfile_bash_version

if [[ "$1" == "restart" ]]; then
  rm -rf "$TARGET_PATH" "$TEMP_PATH"
fi

if [[ ! -f "$TEMP_PATH" ]]; then
  echo -e "${CYAN}Fetching the tags for remote repository...${RESET}"
  CLASH_VERSION=$(git ls-remote --tags git@github.com:MetaCubeX/mihomo.git | cut -d'/' -f3 | grep -x '^v[0-9.]*[0-9]$' | sort -V | tail -n 1)

  DOWNLOAD_URL="https://github.com/MetaCubeX/mihomo/releases/download/$CLASH_VERSION/mihomo-linux-386-$CLASH_VERSION.gz"

  mkdir -p "$TARGET_DIR"
  DOWNLOAD_COMMAND="wget --quiet --show-progress --continue $DOWNLOAD_URL -O $TARGET_PATH"

  echo -e "${YELLOW}Creating the downloading file for downloading clash-meta.gz${RESET}"
  echo "$DOWNLOAD_COMMAND" > $TEMP_PATH
  echo -e "${YELLOW}Creating finished${RESET}"
else
  echo -e "${CYAN}Detected that the downloading file already exists, so just simply start downloading...${RESET}"
fi

eval $(cat $TEMP_PATH)

if gzip --test "$TARGET_PATH" 2> /dev/null; then
  cd "$TARGET_DIR"
  gzip -fd clash-meta.gz
  chmod +x clash-meta
  rm -rf "$TEMP_PATH"
  echo -e "${GREEN}Install finished!!!${RESET}"
else
  echo -e "${RED}Downloaded file has error, so can't extract it.${RESET}"
  echo -e "${RED}Using ${CYAN}install_clash_meta restart${RED} to redownload it${RESET}"
fi
