#!/usr/bin/env bash

set -xe

path=$(cd $(dirname "$0") && pwd)

mkdir -p "$HOME/.config/lynx"
ln -sf "$path/lynx.cfg" "$HOME/.config/lynx/lynx.cfg"
ln -sf "$path/lynx.lss" "$HOME/.config/lynx/lynx.lss"
