set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',*:RGB'
set -g mouse on
set -g focus-events on

# This setting is very useful especially for vim user
# As ANSI escape code is kind of a standard for terminal rendering.
# https://en.wikipedia.org/wiki/ANSI_escape_code
# Sometimes terminal will some send escape sequences to tmux.
# So tmux need wait sometime to know the escape character is a normal keystroke or part of escape sequence.
# Set it to 10ms is OK. This is a unnoticeable delay for vim user.
# Most of the terminals can send the whole escape sequence within 10ms to tmux.
set -g escape-time 10

# Using C-s as the prefix key
unbind C-b
set -g prefix C-s

# Split windows
unbind '"'
unbind %
bind - splitw -v -c '#{pane_current_path}'
bind / splitw -h -c '#{pane_current_path}'

# vi-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind Tab last-window

# statusbar style
set -g renumber-windows on
set -g monitor-activity on
set -g allow-rename on
set -g automatic-rename on
set -g status-interval 1
set -g status-style "bg=#343434,fg=#eeeeee,bold"
set -g mode-style "bg=#ffe900,fg=black"
set -g message-style "fg=black,bg=#ff0000"
set -g window-status-current-style "fg=#f0f000"
set -g window-status-last-style    "fg=#eeeeee"
set -g status-left " ❐ #S "
set -g status-right "#[bg=#4e4e4e] %m/%d #[fg=#f0f000,bg=#343434] %H:%M:%S "
set -g status-right-length 50
set -g status-left-length 20
set -g window-status-format "#I:#W#F"
set -g window-status-current-format "{#I:#{pane_index}}#W#F"
set -g window-status-separator "┇"


# copy mode
set -g set-clipboard external
bind Escape copy-mode
set -g mode-keys vi
bind -T copy-mode-vi q send-keys -X cancel
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi Escape send-keys -X clear-selection
bind -T copy-mode-vi y send-keys -X copy-pipe "xsel -i --clipboard"
unbind -T copy-mode-vi MouseDragEnd1Pane

unbind C-o    # disable swaping panes bind
unbind Space  # disable layout cycling bind

# quit a pane
unbind q
bind q confirm-before -p "quit this window? (y/n)" kill-pane

# reload config file
unbind r
bind r source-file $HOME/.tmux.conf \; display-message "Config reloaded"

# prefix : command mode
# Useful commands: display-panes, swap-pane -s N
