#!/usr/bin/env bash

echo "Not used anymore, as I do not use Arch now, btw" && exit 0

set -xe

path=$(cd $(dirname "$0") && pwd)

comm -12 <(pacman -Qeq | sort) <(pacman -Sql chaotic-aur | sort) > "$path/chaotic-aur.list"
pipx list | grep --extended-regexp '^\W+package' | cut -d ' ' -f5 > "$path/python.list"
rsync -av "$HOME/.config/Code/User/settings.json" "$path/vscode-settings.json"
pacman -Qqem > "$path/aur.list"
