#!/usr/bin/env bash

case $- in
*i*) ;;  # interactive
*) return ;;
esac

_have() { type "$1" &>/dev/null; }
# _have() { command -v "$1" &>/dev/null; }
# shellcheck source=/dev/null
_source_if() { [[ -f "$1" && -r "$1" ]] && source "$1"; }

# https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# fcitx5
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export INPUT_METHOD=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

# time zone
export LC_TIME='zh_CN.UTF-8'

# qt theme
export QT_QPA_PLATFORMTHEME=qt5ct

if _have nvim; then
  export EDITOR=nvim
else
  export EDITOR=vim
fi

export TERMINAL=st
export BROWSER=firefox
export SUDO_ASKPASS="$HOME/dots/scripts/rofi_askpass"

# for 'go`
export GOPATH="$HOME/.local/share/go"
export GOBIN="$HOME/.local/bin"
export GOPROXY=direct
export CGO_ENABLED=0

pathappend () {
  test -d "$1" || return
  case ":$PATH:" in
    *:"$1":*)
      ;;
    *)
      PATH="${PATH:+$PATH:}$1"
  esac
}

pathprepend () {
  test -d "$1" || return
  case ":$PATH:" in
    *:"$1":*)
      ;;
    *)
      PATH="$1${PATH:+":$PATH"}"
  esac
}

pathprepend "$HOME/.cargo/bin"
pathprepend "$HOME/.local/bin"
pathprepend "$HOME/dots/scripts/bin"

ldpathappend () {
  test -d "$1" || return
  case ":$LD_LIBRARY_PATH:" in
    *:"$1":*)
      ;;
    *)
      LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$1"
  esac
}

ldpathprepend () {
  test -d "$1" || return
  case ":$LD_LIBRARY_PATH:" in
    *:"$1":*)
      ;;
    *)
      LD_LIBRARY_PATH="$1${LD_LIBRARY_PATH:+":$LD_LIBRARY_PATH"}"
  esac
}

# bash shell options
shopt -s globstar
shopt -s dotglob
shopt -s extglob

stty werase undef
bind '\C-w:unix-filename-rubout'  # delete word, but don't delete `/`.

# history
HISTFILE=~/.cache/bash_history
HISTTIMEFORMAT='%y-%m-%d %H:%M:%S '
HISTCONTROL=ignoreboth
HISTSIZE=5000
HISTFILESIZE=10000
shopt -s histappend

# disable control-s accidental terminal stops
stty stop undef

__is_in_ssh() {
  pstree -ps $$ | grep --quiet 'sshd(\w*)' && return 0
  [[ -n $TMUX ]] && pstree -ps $(tmux display-message -p "#{client_pid}") | grep --quiet 'sshd(\w*)' && return 0
  return 1
}

__ps1() {
  RESET="\[\e[0m\]"
  GREY="\[\e[1;90m\]"
  RED="\[\e[1;31m\]"
  GREEN="\[\e[1;32m\]"
  YELLOW="\[\e[1;33m\]"
  BLUE="\[\e[1;34m\]"
  MAGENTA="\[\e[1;35m\]"
  CYAN="\[\e[36m\]"

  if git branch > /dev/null 2>&1; then
    # Note that for new repo without commit, git rev-parse --abbrev-ref HEAD will error out.
    if git rev-parse --abbrev-ref HEAD > /dev/null 2>&1; then
      BRANCH="${RESET}(${GREEN}$(git rev-parse --abbrev-ref HEAD)${RESET})"
    else
      BRANCH="${RESET}()"
    fi
  else
    BRANCH=""
  fi

  if command -v deactivate &> /dev/null && [[ -n "${VIRTUAL_ENV_PROMPT}" ]]; then
    VENV_PROMPT="${CYAN}${VIRTUAL_ENV_PROMPT% }${RESET}"
  else
    VENV_PROMPT=""
  fi

  PS1="${RESET}"
  PS1+="${RUST_TFM}"
  PS1+="${VENV_PROMPT}"
  PS1+="${RED}["
  PS1+="${YELLOW}\u"  # username
  PS1+="${GREY}@"
  PS1+="${BLUE}\h "   # hostname
  PS1+="${MAGENTA}\W"    # working directory
  PS1+="${RED}]"
  PS1+="${BRANCH}"
  if __is_in_ssh; then
    PS1+="${RESET} -> (${BLUE}\D{%F}${GREY}@${BLUE}\t${RESET})\n"  # for server(display time)
  fi
  PS1+="${RESET}$ "
}

export PROMPT_COMMAND=__ps1

SetProxy() {
  local ip="${2:-127.0.0.1}"
  local prefix="http://${ip}"
  if echo "$1" | grep -Pq "^\d+$" || ! env | grep -Eq "^(http|https|all)_proxy"; then
    export {http,https,all}_proxy="${prefix}:${1:-7890}"
    env | grep -E --color=always "^(http|https|all)_proxy"
  else
    unset {http,https,all}_proxy
    echo "Unset all proxy"
  fi
} && export SetProxy

# colored man output
# export LESS_TERMCAP_mb=$'\e[1;31m'              # begin blinking
# export LESS_TERMCAP_md=$'\e[1;38;5;74m'         # begin bold
# export LESS_TERMCAP_me=$'\e[0m'                 # end mode
# export LESS_TERMCAP_se=$'\e[0m'                 # end standout-mode
# export LESS_TERMCAP_so=$'\e[38;5;232;48;5;226m' # begin standout-mode - info box
# export LESS_TERMCAP_ue=$'\e[0m'                 # end underline
# export LESS_TERMCAP_us=$'\e[4;38;5;146m'        # begin underline

# export MANPAGER="nvim -u NORC +Man!"
export MANPAGER="nvim +Man!"

export FZF_DEFAULT_OPTS="--no-mouse --height 50% --reverse --multi --info=inline"
for file in /usr/share/fzf/{*,*/*}.bash; do
  _source_if $file
done

alias sudo='sudo -E'
alias grep='grep --color=auto'
alias cp='cp -iv'
alias mv='mv -iv'
alias diff='diff --color -u'
alias rm="echo -e '\e[33m\e[1mWARN\e[0m: Are you sure you want to use \e[31mrm\e[0m, think carefully?'"
alias trash='gio trash'
if _have exa; then
  alias ll='exa -lhg --group-directories-first'
  alias ls='exa --group-directories-first'
  alias l='exa -lhga --group-directories-first'
  alias tree='exa --tree'
else
  alias ls='ls --color=auto --group-directories-first'
  alias ll='ls -lh --color=auto --group-directories-first'
  alias l='ls -lhA --color=auto --group-directories-first'
  alias tree='gio tree'
fi
alias ldf='duf --only local'
alias clear='printf "\e[H\e[2J"'
alias c='printf "\e[H\e[2J"'
_have bat && alias bat='bat --plain'

alias hexedit='hexedit --color'
alias vi="$EDITOR"
alias nvn="$HOME"/.local/nvim-nightly/bin/nvim # nvim nightly
alias sw=devour
alias btl=bluetoothctl
alias nlist='nmcli device wifi list'
alias nconn='nmcli device wifi connect'
alias pc='env | grep -E "^(http|https|all)_proxy"'
alias a8='aria2c -x 8'
alias ydl='yt-dlp --add-metadata -i -f bestvideo+bestaudio'
alias ydlaudio='yt-dlp -f bestaudio -x --audio-format mp3 --audio-quality 0'

alias '?'='ddg'
alias fm=tfm
alias ff=fastfetch

# https://superuser.com/questions/758843/difference-between-global-server-session-and-window-options
alias tmux-autorename="tmux setw -u automatic-rename"  # `-u` will set the option back to global value
# alias tmux-autorename="tmux setw automatic-rename on"

# completion
# shellcheck source=/dev/null
# _have pandoc && . <(pandoc --bash-completion)

# https://gist.github.com/toschneck/2df90c66e0f8d4c6567d69a36bfc5bcd
_have docker && _source_if "$HOME/.local/share/docker/completion.bash"
_source_if "$HOME/dots/scripts/completion/gamebackup"

# NOTE: this file is for the content that don't want to sync
_source_if "$HOME/.user_custom_bashrc"

_have zoxide && eval "$(zoxide init bash --cmd j)"
