#!/usr/bin/env bash

# https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_RUNTIME_DIR="/tmp/user_$(id -u)_XDG_RUNTIME_DIR"
[ -d "$XDG_RUNTIME_DIR" ] || mkdir -m 0700 "$XDG_RUNTIME_DIR"

# https://jiaoshijie.github.io/posts/archlinux_installation/#8-%E5%AE%89%E8%A3%85%E5%AD%97%E4%BD%93%E5%92%8C%E8%BE%93%E5%85%A5%E6%B3%95
export LC_CTYPE='en_US.UTF-8'
export LC_NUMERIC='en_US.UTF-8'
export LC_COLLATE='en_US.UTF-8'
export LC_MONETARY='en_US.UTF-8'
export LC_MESSAGES='en_US.UTF-8'
export LC_PAPER='en_US.UTF-8'
export LC_NAME='en_US.UTF-8'
export LC_ADDRESS='en_US.UTF-8'
export LC_TELEPHONE='en_US.UTF-8'
export LC_MEASUREMENT='en_US.UTF-8'
export LC_IDENTIFICATION='en_US.UTF-8'
# time zone
if locale -a | grep -qiw 'zh_CN.utf-*8'; then
  export LC_TIME='zh_CN.UTF-8'
else
  export LC_TIME='en_US.UTF-8'
fi

# clipboard manager
export CM_DIR="$XDG_CACHE_HOME/clipmenu_cache"

if [[ -n "$BASH_VERSION" ]]; then
    # include .bashrc if it exists
    if [[ -f "$HOME/.bashrc" ]]; then
        # NOTE: don't warn me
        # shellcheck source=/dev/null
        . "$HOME/.bashrc"
    fi
fi

# NOTE: dwm is awesome
type "dwm" &> /dev/null \
  && [ "$(tty)" = "/dev/tty1" ] \
  && ! pgrep -x Xorg >/dev/null \
  && exec startx &> /dev/null
