#!/usr/bin/env bash

case $- in
*i*) ;;  # interactive
*) return ;;
esac

_have() { type "$1" &>/dev/null; }
# _have() { command -v "$1" &>/dev/null; }
# shellcheck source=/dev/null
_source_if() { [[ -f "$1" && -r "$1" ]] && source "$1"; }

# https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# fcitx5
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export INPUT_METHOD=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

# https://jiaoshijie.github.io/posts/archlinux_installation/#8-%E5%AE%89%E8%A3%85%E5%AD%97%E4%BD%93%E5%92%8C%E8%BE%93%E5%85%A5%E6%B3%95
export LC_CTYPE='en_US.UTF-8'
export LC_NUMERIC='en_US.UTF-8'
export LC_COLLATE='en_US.UTF-8'
export LC_MONETARY='en_US.UTF-8'
export LC_MESSAGES='en_US.UTF-8'
export LC_PAPER='en_US.UTF-8'
export LC_NAME='en_US.UTF-8'
export LC_ADDRESS='en_US.UTF-8'
export LC_TELEPHONE='en_US.UTF-8'
export LC_MEASUREMENT='en_US.UTF-8'
export LC_IDENTIFICATION='en_US.UTF-8'
# time zone
if localectl list-locales | grep -qw 'zh_CN.UTF-8'; then
  export LC_TIME='zh_CN.UTF-8'
else
  export LC_TIME='en_US.UTF-8'
fi

# qt theme
export QT_QPA_PLATFORMTHEME=qt5ct

# NOTE: set default `EDITOR` and `MANPAGER`
# https://unix.stackexchange.com/questions/4859/visual-vs-editor-what-s-the-difference
if _have nvim; then
  export VISUAL=nvim

  # If has nvim installed, using nvim as MAN PAGE VIEWER
  # export MANPAGER="nvim -u NORC +Man!"
  export MANPAGER="nvim +Man!"
else
  export VISUAL=vim

  # LESS MAN PAGE COLORS
  export LESS_TERMCAP_mb=$'\e[1;31m'              # begin blinking
  export LESS_TERMCAP_md=$'\e[1;38;5;74m'         # begin bold
  export LESS_TERMCAP_me=$'\e[0m'                 # end mode
  export LESS_TERMCAP_se=$'\e[0m'                 # end standout-mode
  export LESS_TERMCAP_so=$'\e[38;5;232;48;5;226m' # begin standout-mode - info box
  export LESS_TERMCAP_ue=$'\e[0m'                 # end underline
  export LESS_TERMCAP_us=$'\e[4;38;5;146m'        # begin underline
fi
export EDITOR="$VISUAL"

# NOTE: for git
# https://git-scm.com/docs/git-var#_variables
export GIT_EDITOR="$VISUAL"
_have delta && export GIT_PAGER="delta --diff-so-fancy" # NOTE: use `delta` to perform `git diff`

export TERMINAL=st
export BROWSER=firefox
export SUDO_ASKPASS="$HOME/dots/scripts/rofi_askpass"

# for 'go`
export GOPATH="$HOME/.local/share/go"
export GOBIN="$HOME/.local/bin"
export GOPROXY=direct
export CGO_ENABLED=0

pathappend () {
  test -d "$1" || return
  case ":$PATH:" in
    *:"$1":*)
      ;;
    *)
      PATH="${PATH:+$PATH:}$1"
  esac
}

pathprepend () {
  test -d "$1" || return
  case ":$PATH:" in
    *:"$1":*)
      ;;
    *)
      PATH="$1${PATH:+":$PATH"}"
  esac
}

pathprepend "$HOME/.cargo/bin"
pathprepend "$HOME/.local/bin"
pathprepend "$HOME/dots/scripts/bin"

ldpathappend () {
  test -d "$1" || return
  case ":$LD_LIBRARY_PATH:" in
    *:"$1":*)
      ;;
    *)
      LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$1"
  esac
}

ldpathprepend () {
  test -d "$1" || return
  case ":$LD_LIBRARY_PATH:" in
    *:"$1":*)
      ;;
    *)
      LD_LIBRARY_PATH="$1${LD_LIBRARY_PATH:+":$LD_LIBRARY_PATH"}"
  esac
}

# bash shell options
shopt -s globstar
shopt -s dotglob
shopt -s extglob

stty werase undef
bind '\C-w:unix-filename-rubout'  # delete word, but don't delete `/`.

# history
HISTFILE=~/.cache/bash_history
HISTTIMEFORMAT='%y-%m-%d %H:%M:%S '
HISTCONTROL=ignoreboth
HISTSIZE=5000
HISTFILESIZE=10000
shopt -s histappend

# disable control-s accidental terminal stops
stty stop undef

# __is_in_ssh() {
#   pstree -ps $$ | grep --quiet 'sshd(\w*)' && return 0
#   [[ -n $TMUX ]] && pstree -ps $(tmux display-message -p "#{client_pid}") | grep --quiet 'sshd(\w*)' && return 0
#   return 1
# }

__ps1() {
  RESET="\[\e[0m\]"
  GREY="\[\e[1;90m\]"
  RED="\[\e[1;31m\]"
  GREEN="\[\e[1;32m\]"
  YELLOW="\[\e[1;33m\]"
  BLUE="\[\e[1;34m\]"
  MAGENTA="\[\e[1;35m\]"
  CYAN="\[\e[36m\]"

  if git branch > /dev/null 2>&1; then
    # Note that for new repo without commit, git rev-parse --abbrev-ref HEAD will error out.
    if git rev-parse --abbrev-ref HEAD > /dev/null 2>&1; then
      BRANCH="${RESET}(${GREEN}$(git rev-parse --abbrev-ref HEAD)${RESET})"
    else
      BRANCH="${RESET}()"
    fi
  else
    BRANCH=""
  fi

  if command -v deactivate &> /dev/null && [[ -n "${VIRTUAL_ENV_PROMPT}" ]]; then
    VENV_PROMPT="${CYAN}${VIRTUAL_ENV_PROMPT% }${RESET}"
  else
    VENV_PROMPT=""
  fi

  PS1="${RESET}"
  PS1+="${RUST_TFM}"
  PS1+="${VENV_PROMPT}"
  PS1+="${RED}["
  PS1+="${YELLOW}\u"  # username
  PS1+="${GREY}@"
  PS1+="${BLUE}\h "   # hostname
  PS1+="${MAGENTA}\W"    # working directory
  PS1+="${RED}]"
  PS1+="${BRANCH}"
  # if __is_in_ssh; then
  #   PS1+="${RESET} -> (${BLUE}\D{%F}${GREY}@${BLUE}\t${RESET})\n"  # for server(display time)
  # fi
  PS1+="${RESET}$ "
}

export PROMPT_COMMAND=__ps1

SetProxy() {
  local ip="${2:-127.0.0.1}"
  local prefix="http://${ip}"
  if echo "$1" | grep -Pq "^\d+$" || ! env | grep -Eq "^(http|https|all)_proxy"; then
    export {http,https,all}_proxy="${prefix}:${1:-7890}"
    env | grep -E --color=always "^(http|https|all)_proxy"
  else
    unset {http,https,all}_proxy
    echo "Unset all proxy"
  fi
} && export SetProxy

export FZF_DEFAULT_OPTS="--no-mouse --height 50% --reverse --multi --info=inline"
for file in $(find $(find /usr/share/ -type d -name 'fzf' 2> /dev/null) -type f -name '*.bash' 2> /dev/null); do
  _source_if $file
done

# https://linuxhandbook.com/run-alias-as-sudo/
alias sudo='sudo -E ' # NOTE: The space(' ') at the end of the source command is necessary.
alias grep='grep --color=auto'
alias cp='cp -iv'
alias mv='mv -iv'
alias diff='diff --color -u'
alias rm="echo -e '\e[33m\e[1mWARN\e[0m: Are you sure you want to use \e[31mrm\e[0m, think carefully?'"
alias trash='gio trash'
if _have exa; then
  alias ll='exa -lhg --group-directories-first'
  alias ls='exa --group-directories-first'
  alias l='exa -lhga --group-directories-first'
  alias tree='exa --tree'
else
  alias ls='ls --color=auto --group-directories-first'
  alias ll='ls -lh --color=auto --group-directories-first'
  alias l='ls -lhA --color=auto --group-directories-first'
  alias tree='gio tree'
fi
alias ldf='duf --only local'
alias clear='printf "\e[H\e[2J"'
alias c='printf "\e[H\e[2J"'
_have bat && alias bat='bat --plain'

alias hexedit='hexedit --color'
alias vi="$EDITOR"
alias btl=bluetoothctl
alias nlist='nmcli device wifi list'
alias nconn='nmcli device wifi connect'
alias pc='env | grep -E "^(http|https|all)_proxy"'
alias a8='aria2c -x 8'

alias '?'='ddg'
alias fm=tfm
alias ff=fastfetch

# NOTE: nightly nvim version
export NEOVIM_NIGHTLY_PATH="$HOME/.local/nvim-nightly"
alias nvn="$NEOVIM_NIGHTLY_PATH/bin/nvim"

# NOTE: dwm st terminal related
alias sw=devour

# https://superuser.com/questions/758843/difference-between-global-server-session-and-window-options
alias tmux-autorename="tmux setw -u automatic-rename"  # `-u` will set the option back to global value
# alias tmux-autorename="tmux setw automatic-rename on"

if ! shopt -oq posix; then
  # NOTE: basic bash completion
  _source_if $(find /usr/share -type f -name 'bash_completion')

  # completion
  # shellcheck source=/dev/null
  # _have pandoc && . <(pandoc --bash-completion)

  # https://gist.github.com/toschneck/2df90c66e0f8d4c6567d69a36bfc5bcd
  _have docker && _source_if "$HOME/.local/share/docker/completion.bash"
  _source_if "$HOME/dots/scripts/completion/gamebackup"
fi

# NOTE: this file is for the content that don't want to sync
_source_if "$HOME/.user_custom_bashrc"

_have zoxide && eval "$(zoxide init bash --cmd j)"
