#!/usr/bin/env bash

case $- in
*i*) ;;  # interactive
*) return ;;
esac

_have() { type "$1" &>/dev/null; }
# _have() { command -v "$1" &>/dev/null; }
_source_if() { [[ -f "$1" && -r "$1" ]] && source "$1"; }

# NEOVIM PATH
export JSJ_NEOVIM_PATH="$HOME/.local/nvim"
export JSJ_NEOVIM_BIN="$HOME/.local/nvim/bin/nvim"

# NOTE: set default `EDITOR` and `MANPAGER`
# https://unix.stackexchange.com/questions/4859/visual-vs-editor-what-s-the-difference
if _have "$JSJ_NEOVIM_BIN"; then
  export VISUAL="$JSJ_NEOVIM_BIN"

  # If has nvim installed, using nvim as MAN PAGE VIEWER
  # export MANPAGER="nvim -u NORC +Man!"
  export MANPAGER="$JSJ_NEOVIM_BIN +Man!"
else
  export VISUAL=vim

  # LESS MAN PAGE COLORS
  export LESS_TERMCAP_mb=$'\e[1;31m'              # begin blinking
  export LESS_TERMCAP_md=$'\e[1;38;5;74m'         # begin bold
  export LESS_TERMCAP_me=$'\e[0m'                 # end mode
  export LESS_TERMCAP_se=$'\e[0m'                 # end standout-mode
  export LESS_TERMCAP_so=$'\e[38;5;232;48;5;226m' # begin standout-mode - info box
  export LESS_TERMCAP_ue=$'\e[0m'                 # end underline
  export LESS_TERMCAP_us=$'\e[4;38;5;146m'        # begin underline
fi
export EDITOR="$VISUAL"

# NOTE: for git
# https://git-scm.com/docs/git-var#_variables
export GIT_EDITOR="$VISUAL"

# for 'go`
export GOPATH="$HOME/.local/share/go"
export GOBIN="$HOME/.local/bin"
export GOPROXY=direct
export CGO_ENABLED=0

pathappend () {
  test -d "$1" || return
  case ":$PATH:" in
    *:"$1":*)
      ;;
    *)
      PATH="${PATH:+$PATH:}$1"
  esac
}

pathprepend () {
  test -d "$1" || return
  case ":$PATH:" in
    *:"$1":*)
      ;;
    *)
      PATH="$1${PATH:+":$PATH"}"
  esac
}

pathprepend "$HOME/.cargo/bin"
pathprepend "$HOME/.local/bin"
pathprepend "$HOME/dots/scripts/bin"

ldpathappend () {
  test -d "$1" || return
  case ":$LD_LIBRARY_PATH:" in
    *:"$1":*)
      ;;
    *)
      LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$1"
  esac
}

ldpathprepend () {
  test -d "$1" || return
  case ":$LD_LIBRARY_PATH:" in
    *:"$1":*)
      ;;
    *)
      LD_LIBRARY_PATH="$1${LD_LIBRARY_PATH:+":$LD_LIBRARY_PATH"}"
  esac
}

# bash shell options
shopt -s globstar
shopt -s dotglob
shopt -s extglob

stty werase undef
bind '\C-w:unix-filename-rubout'  # delete word, but don't delete `/`.

# history
HISTFILE=~/.cache/bash_history
HISTTIMEFORMAT='%y-%m-%d %H:%M:%S '
HISTCONTROL=ignoreboth
HISTSIZE=5000
HISTFILESIZE=10000
shopt -s histappend

# disable control-s accidental terminal stops
stty stop undef

__ps1() {
  RESET="\[\e[0m\]"
  GREY="\[\e[1;90m\]"
  RED="\[\e[1;31m\]"
  GREEN="\[\e[1;32m\]"
  YELLOW="\[\e[1;33m\]"
  BLUE="\[\e[1;34m\]"
  MAGENTA="\[\e[1;35m\]"
  CYAN="\[\e[36m\]"

  if git branch > /dev/null 2>&1; then
    # Note that for new repo without commit, git rev-parse --abbrev-ref HEAD will error out.
    if git rev-parse --abbrev-ref HEAD > /dev/null 2>&1; then
      BRANCH="${RESET}(${GREEN}$(git rev-parse --abbrev-ref HEAD)${RESET})"
    else
      BRANCH="${RESET}()"
    fi
  else
    BRANCH=""
  fi

  if command -v deactivate &> /dev/null && [[ -n "${VIRTUAL_ENV_PROMPT}" ]]; then
    VENV_PROMPT="${CYAN}${VIRTUAL_ENV_PROMPT% }${RESET}"
  else
    VENV_PROMPT=""
  fi

  PS1="${RESET}"
  PS1+="${RUST_TFM}"
  PS1+="${VENV_PROMPT}"
  PS1+="${RED}["
  PS1+="${YELLOW}\u"  # username
  PS1+="${GREY}@"
  PS1+="${BLUE}\h "   # hostname
  PS1+="${MAGENTA}\W"    # working directory
  PS1+="${RED}]"
  PS1+="${BRANCH}"
  PS1+="${RESET} -> (${BLUE}\D{%F}${GREY}@${BLUE}\t${RESET})\n"  # Time
  PS1+="${RESET}$ "
}

export PROMPT_COMMAND=__ps1

SetProxy() {
  local ip="${2:-127.0.0.1}"
  local prefix="http://${ip}"
  if echo "$1" | grep -Pq "^\d+$" || ! env | grep -Eq "^(http|https|all)_proxy"; then
    export {http,https,all}_proxy="${prefix}:${1:-7890}"
    env | grep -E --color=always "^(http|https|all)_proxy"
  else
    unset {http,https,all}_proxy
    echo "Unset all proxy"
  fi
} && export SetProxy

export FZF_DEFAULT_OPTS="--no-mouse --height 50% --reverse --multi --info=inline"
# ArchLinux
_source_if '/usr/share/fzf/completion.bash'
_source_if '/usr/share/fzf/key-bindings.bash'
# Ubuntu
_source_if '/usr/share/doc/fzf/examples/key-bindings.bash'

# https://linuxhandbook.com/run-alias-as-sudo/
alias sudo='sudo -E ' # NOTE: The space(' ') at the end of the source command is necessary.
alias grep='grep --color=auto'
alias cp='cp -iv'
alias mv='mv -iv'
alias diff='diff --color -u'
alias rm="echo -e '\e[33m\e[1mWARN\e[0m: Are you sure you want to use \e[31mrm\e[0m, think carefully?'"
if _have trashy; then
  alias trash='trashy put'
  alias trash_list='trashy list'
  alias trash_empty_all='trashy empty --all'
fi
if _have exa; then
  alias ll='exa -lhg --group-directories-first'
  alias ls='exa --group-directories-first'
  alias l='exa -lhga --group-directories-first'
  alias tree='exa --tree'
else
  alias ls='ls --color=auto --group-directories-first'
  alias ll='ls -lh --color=auto --group-directories-first'
  alias l='ls -lhA --color=auto --group-directories-first'
  alias tree='gio tree'
fi
alias ldf='duf --only local'
alias clear='printf "\e[H\e[2J"'
alias c='printf "\e[H\e[2J"'

alias hexedit='hexedit --color'
alias vi="$EDITOR"
alias nlist='nmcli device wifi list'
alias nconn='nmcli device wifi connect'
alias pc='env | grep -E "^(http|https|all)_proxy"'
alias a8='aria2c -x 8'

alias '?'='ddg'
alias fm=tfm
alias ff=fastfetch

# NOTE: nightly nvim version
export JSJ_NEOVIM_NIGHTLY_PATH="$HOME/.local/nvim-nightly"
alias nvn="$JSJ_NEOVIM_NIGHTLY_PATH/bin/nvim"

# https://superuser.com/questions/758843/difference-between-global-server-session-and-window-options
alias tmux-autorename="tmux setw -u automatic-rename"  # `-u` will set the option back to global value
# alias tmux-autorename="tmux setw automatic-rename on"

if ! shopt -oq posix; then
  # ArchLinux,Ubuntu
  _source_if '/usr/share/bash-completion/bash_completion'

  # _have pandoc && . <(pandoc --bash-completion)
fi

# NOTE: this file is for the content that don't want to sync
_source_if "$HOME/.user_custom_bashrc"

_have zoxide && eval "$(zoxide init bash --cmd j)"
